### PR TITLE
update KillAura.kt

### PR DESCRIPTION
**Pull request by opZywl**
Killaura SwitchDelay and BlockRange and Armor Mode and New Marks

### CODE REVIEW

**Comment by liulihaocai** [comment]
hmm wheres the GLUtils

**Comment by liulihaocai** [comment]
and some values like blockModeValue just created not called in code

**Comment by opZywl** [comment]
> hmm wheres the GLUtils
I will send GLU

**Comment by opZywl** [comment]
> hmm wheres the GLUtils

#103

**Pull request closed without merging**
